development:
  adapter: mysql
  encoding: utf8
  database: dev_igoreanarachel
  username: root
  password:

test:
  adapter: mysql
  encoding: utf8
  database: test_igoreanarachel
  username: root
  password:

production:
  development
