development:
  adapter: mysql
  encoding: utf8
  database: igoreanarachel_development
  username: root
  password:

test:
  adapter: mysql
  encoding: utf8
  database: igoreanarachel_test
  username: root
  password:

production:
  development
